name: Update meta-submodule

on:
  workflow_dispatch:
  schedule:
    - cron: "18 9 * * *"

jobs:
  update:
    permissions:
      pull-requests: write
      contents: write
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/update-from-meta.yaml@c22aee119490b79229eb3f8489d513e01a4e370a
